name: time-push
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.0；由于未提供具体版本，请选择合适的Python版本
      
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai；使用timedatectl命令来设置时区

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      
      - name: Daily morning
        run: |
          python3 main.py
